#+title: HTTP Messages
#+author: Jake Shilling
#+email: shilling.jake@gmail.com
#+description: Notes on the format of HTTP/1.1 messages

These are my notes on the current HTTP/1.1 specifications. I'm reading
off [[https://tools.ietf.org/html/rfc7230][this document]].

* Syntax Notation

ALPHA  = letters
CR     = carriage return
CRLF   = CR LF
CTL    = controls
DIGIT  = 0-9
DQUOTE = double quote
HEXDIG = hexadecimal digit
HTAB   = horizontal tab
LF     = line feed
OCTET  = any 8-bit sequence of data
SP     = space
VCHAR  = any visible character

* Message Format

HTTP-message = [[*Start Line][start-line]]
               *( [[*Header Fields][header-field]] CRLF )
               CRLF
               [ message-body ]

* Start Line

start-line   = [[*Request Line][request-line]] / status-line

* Request Line

request-line = method SP request-target SP HTTP-version CRLF
method       = token

* TODO Request Target
- Starts at 5.3

* Header Fields

header-field  = field-name ":" OWS field-value OWS

field-name    = token
field-value   = *( field-content / obs-fold )
field-content = field-vchar [ !*( SP / HTAB ) field-vchar ]
field-vchar   = VCHAR / obs-text

obs-fold      = CRLF 1*( SP / HTAB )

* Field Value Components

token         = 1*tchar

tchar         = "!" / "#" / "$" / "%" / "&" / "'" / "*" / "+" / "-" / "." /
                "^" / "_" / "`" / "|" / "~" / DIGIT / ALPHA

quoted-string = DQUOTE *( qdtext / quoted-pair ) DQUOTE
qdtext        = HTAB / SP / %x21 / %23-5B / %x5D-7E / obs-text
obs-text      = %x80-FF

Comments are only allowed in fields containing "comment" as pair of
their field value definition.

comment       = "(" *( ctext / quoted-pair / comment ) ")"
ctext         = HTAB / SP / %x21-27 / %x2A-5B / %x5D-7E / obs-text

quoted-pair   = "\" ( HTAB / SP / VCHAR / obs-text )

* Message Body

message-body = *OCTET

The presence of a message body in a request is signaled by a
Content-Length or Transfer-Encoding header field. Request message
framing is independent of method semantics, even if the method does
not define any use for a method body.

A sender MUST NOT send a Content-Length header field in any message
that contains a Transfer-Encoding header field.

A user agent SHOULD send a Content-Length in a request message when no
Transfer-Encoding is sent and the request method defines a meaning for
an enclosed payload body.

A user agent SHOULD NOT send a Content-Length header field when the
request message does not contain a payload body and the method
semantics do not anticipate such a body.

** Transfer-Encoding

Transfer-Encoding  = 1#transfer-coding

transfer-coding    = "chunked"
                   / "compress"
                   / "deflate"
                   / "gzip"
                   / transfer-extension
transfer-extension = token *( OWS ";" OWS transfer-parameter )

transfer-parameter = token BWS "=" BWS ( token / quoted-string )

** Content-Length

Content-Length = 1*DIGIT

** TODO Take more notes on chunking and compressing message body
- Starts at 4.1

* Whitespace

OWS = *( SP / HTAB )
      ; optional whitespace
RWS = 1*( SP / HTAB )
      ; required whitespace
BWS = OWS
      ; "bad" whitespace
